### PR TITLE
WIP: bump analyzer to ^0.40.0

### PR DESCRIPTION
**Pull request by lukaszkolodziejczyk**

### CODE REVIEW

**Comment by mk13** [comment]
I took another look at the travis errors, this may be related to enabling null-safety. Can you try the following outlined here? https://dart.dev/null-safety#enable-null-safety

**Comment by szepeshazi** [comment]
Does this mean that pagloader's analyzer 0.40.x support will only come together with some null safe dependencies? Currently this package is the only one blocking us from upgrading our Angular 5.3 application to Angular 6.0.1. 

Is there any upgrade path you see that we might take towards Angular 6.0.1 (without moving to beta SDK and null safety)?

**Comment by GenesisTMS** [comment]
Current workaroung to use pageloader in angular 6.0.1 is to fork this repo and patch it with this PR (and update pubspec.yaml) and use `dependency_overrides`.  

like this:
```
dev_dependencies:
  pageloader: any
dependency_overrides:
  pageloader:
    git: 
      url: <patched-repo>
```

**Comment by szepeshazi** [comment]
> Current workaroung to use pageloader in angular 6.0.1 is to fork this repo and patch it with this PR (and update pubspec.yaml) and use `dependency_overrides`.
> 
> like this:
> 
> ```
> dev_dependencies:
>   pageloader: any
> dependency_overrides:
>   pageloader:
>     git: 
>       url: <patched-repo>
> ```

Yes, but this would bring `built_value_generator: ^8.0.0-nullsafety` as dependency in my project. I'd like to avoid the whole null safe frenzy until it reaches the level of maturity and stability required for a production application.

**Comment by GenesisTMS** [comment]
> Yes, but this would bring `built_value_generator: ^8.0.0-nullsafety` as dependency in my project. I'd like to avoid the whole null safe frenzy until it reaches the level of maturity and stability required for a production application.

I do not have `built

**Comment by szepeshazi** [comment]
> > Yes, but this would bring `built_value_generator: ^8.0.0-nullsafety` as dependency in my project. I'd like to avoid the whole null safe frenzy until it reaches the level of maturity and stability required for a production application.
> 
> I do not have `built_value_generator` as dependency in my project.

It's a transitive dependency brought by pageloader. Check this PR's `pubspec.yaml` file.

**Comment by GenesisTMS** [comment]
> It's a transitive dependency brought by pageloader. Check this PR's pubspec.yaml file.
```
pub upgrade | grep built
  built_collection 4.3.2
  built_value 7.1.0
Warning: You are using these overridden dependencies:
! pageloader 3.3.1 from git <patched-pageloader>
```

**Pull request closed without merging**
