### PR TITLE
Adds support for analyzer 0.40.0

### PR DESCRIPTION
**Pull request by LukeyBeachBoy**

### CODE REVIEW

**Comment by LukeyBeachBoy** [comment]
@googlebot I signed it!

**Comment by LukeyBeachBoy** [comment]
@googlebot I fixed it.

**Comment by agilob** [comment]
pageloader with analyzer <0.40 is the only blocker for me to adopt angular ^6.0.0

**Comment by jguitar** [comment]
@LukeyBeachBoy could you update this PR to fix the CI?

**Comment by mk13** [comment]
This PR isn't compatible with analyzer changes. #217 should fix this though.

**Pull request closed without merging**
